# Generated by Django 4.2.2 on 2023-06-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_cart_category_product_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('discount', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled')], max_length=225, null=True)),
                ('payment_method', models.CharField(choices=[('paystack', 'paystack'), ('transfer', 'transfer')], default='paystack', max_length=225, null=True)),
                ('payment_complete', models.BooleanField(default=False, null=True)),
                ('ref', models.CharField(max_length=255, null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
            ],
        ),
    ]
